### ISSUE TITLE
Project name change request

### ISSUE THREAD

**Issue by RTimothyEdwards** [JYSquare2/sky130_icrg_ip__ulpcomp#1]
Quick request:  The name of the project (and the repository) should not have "_ef_" in the name, which is specifically for "Efabless".  We would like you to own your hard work!  Please replace "ef" with something reflecting yourself, or your design team, or school.  Thanks!

**Comment by JYSquare2** [comment]
Completed, thank you.

**Comment by JYSquare2** [comment]
Completed, thank you.
